In [1]:
import numpy as np
a = np.array([[1, 4], [3, 4], [6, 7]])
b = {i for j in a for i in j}
print(a[[0, 1], 0])

[1 3]


In [2]:
from operator import itemgetter

a={1:2, 3:4, 5:6, 7:8}
keys = [3, 5]
ans = list(itemgetter(*keys)(a))
print(ans)
M= np.zeros((7, 7))
M[0, ans] = 1
print(M)

[4, 6]
[[0. 0. 0. 0. 1. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [3]:
a, b, c, d, e, f = 1, 2, 3, 4, 5, 6
a, b, c = a+d, b+e, c+f

In [4]:
import numpy as np
kk = np.array([[1, 2, 3], [3, 4, 5]])
kk[np.arange(2), :]

array([[1, 2, 3],
       [3, 4, 5]])

In [5]:
sen = [['abc', 'def', 'ehiggg'], ['def', 'ggg', 'abcd', 'ei'], ['111', '222']]
kk = max([len(i) for i in sen])
sens = [(i + ['0']*(kk-len(i))) for i in sen]
print(sens)

[['abc', 'def', 'ehiggg', '0'], ['def', 'ggg', 'abcd', 'ei'], ['111', '222', '0', '0']]


In [6]:
import torch
from torch.nn.utils.rnn import pack_padded_sequence, pad_packed_sequence
seq = torch.tensor([[1,2,0], [3,0,0], [4,5,6]])
lens = [2, 1, 3]
packed = pack_padded_sequence(seq, lens, batch_first=True, enforce_sorted=False)
packed

PackedSequence(data=tensor([4, 1, 3, 5, 2, 6]), batch_sizes=tensor([3, 2, 1]), sorted_indices=tensor([2, 0, 1]), unsorted_indices=tensor([1, 2, 0]))

In [7]:
import torch.nn as nn
import torch
m = nn.Conv1d(16, 33, 3, 1, 1)
input = torch.randn(20, 16, 50)
output = m(input)

In [8]:
import torch
print(torch.cuda.is_available())

True
