In [26]:
import numpy as np
a = np.array([[1, 4], [3, 4], [6, 7]])
b = {i for j in a for i in j}
print(a[[0, 1], 0])

[1 3]


In [20]:
from operator import itemgetter

a={1:2, 3:4, 5:6, 7:8}
keys = [3, 5]
ans = list(itemgetter(*keys)(a))
print(ans)
M= np.zeros((7, 7))
M[0, ans] = 1
print(M)

[4, 6]
[[0. 0. 0. 0. 1. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [7]:
a, b, c, d, e, f = 1, 2, 3, 4, 5, 6
a, b, c = a+d, b+e, c+f